use linux_raw_sys::general::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApeSyscall {
    Dup,
    Dup3,
    Read,
    Write,
    Readv,
    Writev,
    OpenAt,
    ReadlinkAt,
    NewFstatAt,
    Fstat,
    Getdents64,
    MkdirAt,
    UnlinkAt,
    LinkAt,
    Mount,
    Umount2,
    Pipe2,
    Close,
    GetCwd,
    Chdir,
    Fchdir,
    Chroot,
    Exit,
    ExitGroup,
    Uname,
    GetPid,
    GetTid,
    GetPpid,
    SetTidAddress,
    Brk,
    Mmap,
    Mprotect,
    Munmap,
    Mremap,
    Lseek,
    Fcntl,
    Ioctl,
    Execve,
    RtSigaction,
    RtSigsuspend,
    RtSigprocmask,
    RtSigpending,
    RtSigtimedwait,
    RtSigreturn,
    Prlimit64,
    ClockGettime,
    Gettimeofday,
    Utimensat,
    Times,
    Nanosleep,
    Ppoll,
    Getrandom,
    Getuid,
    Geteuid,
    Getgid,
    Getegid,
    Clone,
    Wait4,
    Setsid,
    Getsid,
    Setpgid,
    Getpgid,
    Kill,
    Reboot,
    SchedYield,
    Prctl,
    Futex,
    ClockGetres,
    ClockNanosleep,
    CopyFileRange,
    EpollCreate1,
    EpollCtl,
    EpollPwait,
    MemfdCreate,
    Faccessat,
    Fadvise64,
    Fchmod,
    Fchmodat,
    Fchown,
    Fchownat,
    Fstatfs,
    Pread64,
    Preadv,
    Statx,
    Pselect6,
    Pwrite64,
    Pwritev,
    Setrlimit,
    Getrlimit,
    RenameAt,
    RenameAt2,
    RtTgsigqueueinfo,
    Sendfile,
    Shmat,
    Shmctl,
    Shmdt,
    Shmget,
    Sigaltstack,
    Splice,
    Statfs,
    SymlinkAt,
    Tgkill,
    Tkill,
    Socket,
    Bind,
    Getsockname,
    Setsockopt,
    Sendto,
    Recvfrom,
    Shutdown,
    Listen,
    Accept,
    Connect,
    SchedGetaffinity,
    SchedSetaffinity,
    Truncate,
    Ftruncate,
    // The following syscalls are not implemented yet, and will be handled by stub functions.
    Unsupported,
    StubBypass,
    StubKill,
    StubOpen,
    StubNOMSG,
    StubSRCH,
    StubFAULT,
    StubBADF,
    StubINVAL,
    StubPERM,
}

#[allow(non_upper_case_globals)]
pub fn decode_ape_syscall(sys_num: usize) -> ApeSyscall {
    match sys_num as u32 {
        __NR_read => ApeSyscall::Read,
        __NR_write => ApeSyscall::Write,
        __NR_mmap => ApeSyscall::Mmap,
        __NR_ioctl => ApeSyscall::Ioctl,
        __NR_writev => ApeSyscall::Writev,
        __NR_sched_yield => ApeSyscall::SchedYield,
        __NR_nanosleep => ApeSyscall::Nanosleep,
        __NR_getpid => ApeSyscall::GetPid,
        __NR_getppid => ApeSyscall::GetPpid,
        __NR_exit => ApeSyscall::Exit,
        __NR_gettimeofday => ApeSyscall::Gettimeofday,
        __NR_getcwd => ApeSyscall::GetCwd,
        __NR_dup => ApeSyscall::Dup,
        __NR_dup3 => ApeSyscall::Dup3,
        __NR_fcntl => ApeSyscall::Fcntl,
        __NR_clone => ApeSyscall::Clone,
        __NR_wait4 => ApeSyscall::Wait4,
        __NR_close => ApeSyscall::Close,
        __NR_chdir => ApeSyscall::Chdir,
        __NR_execve => ApeSyscall::Execve,
        __NR_openat => ApeSyscall::OpenAt,
        __NR_getdents64 | 61 => ApeSyscall::Getdents64,
        __NR_linkat => ApeSyscall::LinkAt,
        __NR_uname => ApeSyscall::Uname,
        __NR_fstat => ApeSyscall::Fstat,
        __NR_mount => ApeSyscall::Mount,
        __NR_umount2 => ApeSyscall::Umount2,
        __NR_newfstatat => ApeSyscall::NewFstatAt,
        __NR_statx => ApeSyscall::Statx,
        __NR_munmap => ApeSyscall::Munmap,
        __NR_mprotect => ApeSyscall::Mprotect,
        __NR_times => ApeSyscall::Times,
        __NR_brk => ApeSyscall::Brk,
        __NR_set_tid_address => ApeSyscall::SetTidAddress,
        __NR_clock_getres => ApeSyscall::ClockGetres,
        __NR_clock_gettime => ApeSyscall::ClockGettime,
        __NR_clock_nanosleep => ApeSyscall::ClockNanosleep,
        __NR_copy_file_range => ApeSyscall::CopyFileRange,
        __NR_epoll_create1 => ApeSyscall::EpollCreate1,
        __NR_epoll_ctl => ApeSyscall::EpollCtl,
        __NR_epoll_pwait => ApeSyscall::EpollPwait,
        __NR_exit_group => ApeSyscall::ExitGroup,
        __NR_faccessat => ApeSyscall::Faccessat,
        __NR_fadvise64 => ApeSyscall::Fadvise64,
        __NR_fchdir => ApeSyscall::Fchdir,
        __NR_fchmod => ApeSyscall::Fchmod,
        __NR_fchmodat => ApeSyscall::Fchmodat,
        __NR_fchown => ApeSyscall::Fchown,
        __NR_fchownat => ApeSyscall::Fchownat,
        __NR_fstatfs => ApeSyscall::Fstatfs,
        __NR_futex => ApeSyscall::Futex,
        __NR_getegid => ApeSyscall::Getegid,
        __NR_geteuid => ApeSyscall::Geteuid,
        __NR_setpgid => ApeSyscall::Setpgid,
        __NR_getpgid => ApeSyscall::Getpgid,
        __NR_getgid => ApeSyscall::Getgid,
        __NR_getrandom => ApeSyscall::Getrandom,
        __NR_gettid => ApeSyscall::GetTid,
        __NR_getuid => ApeSyscall::Getuid,
        __NR_kill => ApeSyscall::Kill,
        __NR_lseek => ApeSyscall::Lseek,
        __NR_mkdirat => ApeSyscall::MkdirAt,
        __NR_ppoll => ApeSyscall::Ppoll,
        __NR_pread64 => ApeSyscall::Pread64,
        __NR_preadv => ApeSyscall::Preadv,
        __NR_prlimit64 => ApeSyscall::Prlimit64,
        __NR_pselect6 => ApeSyscall::Pselect6,
        __NR_pwrite64 => ApeSyscall::Pwrite64,
        __NR_pwritev => ApeSyscall::Pwritev,
        __NR_setrlimit => ApeSyscall::Setrlimit,
        __NR_getrlimit => ApeSyscall::Getrlimit,
        __NR_readlinkat => ApeSyscall::ReadlinkAt,
        __NR_readv => ApeSyscall::Readv,
        __NR_renameat2 => ApeSyscall::RenameAt2,
        __NR_rt_sigaction => ApeSyscall::RtSigaction,
        __NR_rt_sigpending => ApeSyscall::RtSigpending,
        __NR_rt_sigprocmask => ApeSyscall::RtSigprocmask,
        __NR_rt_sigsuspend => ApeSyscall::RtSigsuspend,
        __NR_rt_tgsigqueueinfo => ApeSyscall::RtTgsigqueueinfo,
        __NR_sendfile => ApeSyscall::Sendfile,
        __NR_shmat => ApeSyscall::Shmat,
        __NR_shmctl => ApeSyscall::Shmctl,
        __NR_shmdt => ApeSyscall::Shmdt,
        __NR_shmget => ApeSyscall::Shmget,
        __NR_sigaltstack => ApeSyscall::Sigaltstack,
        __NR_splice => ApeSyscall::Splice,
        __NR_statfs => ApeSyscall::Statfs,
        __NR_symlinkat => ApeSyscall::SymlinkAt,
        __NR_tgkill => ApeSyscall::Tgkill,
        __NR_tkill => ApeSyscall::Tkill,
        __NR_unlinkat => ApeSyscall::UnlinkAt,
        __NR_utimensat => ApeSyscall::Utimensat,
        __NR_socket => ApeSyscall::Socket,
        __NR_bind => ApeSyscall::Bind,
        __NR_getsockname => ApeSyscall::Getsockname,
        __NR_setsockopt => ApeSyscall::Setsockopt,
        __NR_sendto => ApeSyscall::Sendto,
        __NR_recvfrom => ApeSyscall::Recvfrom,
        __NR_shutdown => ApeSyscall::Shutdown,
        __NR_listen => ApeSyscall::Listen,
        __NR_accept => ApeSyscall::Accept,
        __NR_connect => ApeSyscall::Connect,
        __NR_sync => ApeSyscall::StubBypass,
        __NR_fsync => ApeSyscall::StubBypass,
        __NR_truncate => ApeSyscall::Truncate,
        __NR_ftruncate => ApeSyscall::Ftruncate,
        __NR_syslog => ApeSyscall::StubBypass,
        __NR_get_robust_list => ApeSyscall::StubBypass,
        __NR_set_robust_list => ApeSyscall::StubBypass,
        __NR_setgid => ApeSyscall::StubBypass,
        __NR_setuid => ApeSyscall::StubBypass,
        __NR_umask => ApeSyscall::StubBypass,
        __NR_get_mempolicy => ApeSyscall::StubBypass,
        __NR_socketpair => ApeSyscall::StubBypass,
        __NR_sched_getaffinity => ApeSyscall::SchedGetaffinity,
        __NR_sched_setaffinity => ApeSyscall::SchedSetaffinity,
        __NR_memfd_create => ApeSyscall::MemfdCreate,
        __NR_memfd_secret => ApeSyscall::StubOpen,
        __NR_open_tree => ApeSyscall::StubOpen,
        __NR_fsopen => ApeSyscall::StubOpen,
        __NR_fspick => ApeSyscall::StubOpen,
        __NR_bpf => ApeSyscall::StubOpen,
        __NR_io_uring_setup => ApeSyscall::StubOpen,
        __NR_perf_event_open => ApeSyscall::StubOpen,
        __NR_userfaultfd => ApeSyscall::StubOpen,
        __NR_inotify_init1 => ApeSyscall::StubOpen,
        __NR_pidfd_open => ApeSyscall::StubOpen,
        __NR_eventfd2 => ApeSyscall::StubOpen,
        __NR_timerfd_create => ApeSyscall::StubOpen,
        __NR_signalfd4 => ApeSyscall::StubOpen,
        __NR_fanotify_init => ApeSyscall::StubOpen,
        __NR_sched_setparam => ApeSyscall::StubBypass,
        __NR_sched_getparam => ApeSyscall::StubBypass,
        __NR_sched_setscheduler => ApeSyscall::StubBypass,
        __NR_sched_getscheduler => ApeSyscall::StubBypass,
        __NR_msync => ApeSyscall::StubBypass,
        __NR_setresuid => ApeSyscall::StubBypass,
        __NR_setsid => ApeSyscall::StubBypass,
        __NR_setitimer => ApeSyscall::StubBypass,
        __NR_getitimer => ApeSyscall::StubBypass,
        __NR_mq_open => ApeSyscall::StubBypass,
        __NR_mq_unlink => ApeSyscall::StubBypass,
        __NR_mq_timedsend => ApeSyscall::StubBypass,
        __NR_mq_timedreceive => ApeSyscall::StubBypass,
        __NR_mq_getsetattr => ApeSyscall::StubBypass,
        __NR_mknodat => ApeSyscall::StubBypass,
        __NR_setregid => ApeSyscall::StubBypass,
        __NR_fallocate => ApeSyscall::StubBypass,
        __NR_flock => ApeSyscall::StubBypass,
        __NR_sendmsg => ApeSyscall::StubBypass,
        __NR_sendmmsg => ApeSyscall::StubBypass,
        __NR_getresuid => ApeSyscall::StubBypass,
        __NR_setresgid => ApeSyscall::StubBypass,
        __NR_getresgid => ApeSyscall::StubBypass,
        __NR_setfsgid => ApeSyscall::StubBypass,
        __NR_unshare => ApeSyscall::StubBypass,
        __NR_chroot => ApeSyscall::StubBypass,
        __NR_pivot_root => ApeSyscall::StubBypass,
        __NR_msgget => ApeSyscall::StubBypass,
        __NR_msgctl => ApeSyscall::StubBypass,
        __NR_msgsnd => ApeSyscall::StubBypass,
        __NR_mlock => ApeSyscall::StubBypass,
        __NR_munlock => ApeSyscall::StubBypass,
        __NR_getrusage => ApeSyscall::StubBypass,
        __NR_timerfd_settime => ApeSyscall::StubBypass,
        __NR_timerfd_gettime => ApeSyscall::StubBypass,
        __NR_semget => ApeSyscall::StubBypass,
        __NR_prctl => ApeSyscall::StubBypass,
        __NR_setxattr => ApeSyscall::StubBypass,
        __NR_removexattr => ApeSyscall::StubBypass,
        __NR_setreuid => ApeSyscall::StubBypass,
        __NR_personality => ApeSyscall::StubBypass,
        __NR_madvise => ApeSyscall::StubBypass,
        __NR_getsockopt => ApeSyscall::StubFAULT,
        __NR_msgrcv => ApeSyscall::StubNOMSG,
        __NR_setpriority => ApeSyscall::StubSRCH,
        __NR_mq_notify => ApeSyscall::StubBADF,
        __NR_open_by_handle_at => ApeSyscall::StubINVAL,
        __NR_name_to_handle_at => ApeSyscall::StubFAULT,
        __NR_adjtimex => ApeSyscall::StubPERM,
        __NR_getpeername => ApeSyscall::StubFAULT,
        __NR_setdomainname => ApeSyscall::StubINVAL,
        __NR_sethostname => ApeSyscall::StubINVAL,
        __NR_semctl => ApeSyscall::StubFAULT,
        __NR_sched_rr_get_interval => ApeSyscall::StubINVAL,
        __NR_getpriority => ApeSyscall::StubSRCH,
        __NR_process_vm_writev => ApeSyscall::StubINVAL,
        _ => ApeSyscall::Unsupported,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FutexOpClass {
    Wake,
    Wait,
    Other,
}

pub fn classify_futex_op(futex_op: usize) -> FutexOpClass {
    let cmd = futex_op & FUTEX_CMD_MASK as usize;
    match cmd as u32 {
        FUTEX_WAKE | FUTEX_WAKE_PRIVATE => FutexOpClass::Wake,
        FUTEX_WAIT | FUTEX_WAIT_PRIVATE | FUTEX_WAIT_BITSET | FUTEX_WAIT_BITSET_PRIVATE => {
            FutexOpClass::Wait
        }
        _ => FutexOpClass::Other,
    }
}
