use linux_raw_sys::general::*;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApeSyscall {
    Dup,
    Dup3,
    Read,
    Write,
    Readv,
    Writev,
    OpenAt,
    NewFstatAt,
    Fstat,
    Getdents64,
    MkdirAt,
    UnlinkAt,
    LinkAt,
    Mount,
    Umount2,
    Pipe2,
    Close,
    GetCwd,
    Chdir,
    Fchdir,
    Chroot,
    Exit,
    ExitGroup,
    Uname,
    GetPid,
    GetTid,
    GetPpid,
    SetTidAddress,
    Brk,
    Mmap,
    Mprotect,
    Munmap,
    Mremap,
    Lseek,
    Fcntl,
    Ioctl,
    Execve,
    RtSigaction,
    RtSigsuspend,
    RtSigprocmask,
    RtSigpending,
    RtSigtimedwait,
    RtSigreturn,
    SetRobustList,
    Prlimit64,
    ClockGettime,
    Gettimeofday,
    Times,
    Nanosleep,
    Ppoll,
    Getrandom,
    Getuid,
    Geteuid,
    Getgid,
    Getegid,
    Clone,
    Wait4,
    Setsid,
    Getsid,
    Setpgid,
    Getpgid,
    Kill,
    Reboot,
    SchedYield,
    Prctl,
    Futex,
    Unsupported,
}

#[allow(non_upper_case_globals)]
pub fn decode_ape_syscall(sys_num: usize) -> ApeSyscall {
    match sys_num as u32 {
        __NR_dup => ApeSyscall::Dup,
        __NR_dup3 => ApeSyscall::Dup3,
        __NR_read => ApeSyscall::Read,
        __NR_write => ApeSyscall::Write,
        __NR_readv => ApeSyscall::Readv,
        __NR_writev => ApeSyscall::Writev,
        __NR_openat => ApeSyscall::OpenAt,
        __NR_newfstatat => ApeSyscall::NewFstatAt,
        __NR_fstat => ApeSyscall::Fstat,
        __NR_getdents64 => ApeSyscall::Getdents64,
        __NR_mkdirat => ApeSyscall::MkdirAt,
        __NR_unlinkat => ApeSyscall::UnlinkAt,
        __NR_linkat => ApeSyscall::LinkAt,
        __NR_mount => ApeSyscall::Mount,
        __NR_umount2 => ApeSyscall::Umount2,
        __NR_pipe2 => ApeSyscall::Pipe2,
        __NR_close => ApeSyscall::Close,
        __NR_getcwd => ApeSyscall::GetCwd,
        __NR_chdir => ApeSyscall::Chdir,
        __NR_fchdir => ApeSyscall::Fchdir,
        __NR_chroot => ApeSyscall::Chroot,
        __NR_exit => ApeSyscall::Exit,
        __NR_exit_group => ApeSyscall::ExitGroup,
        __NR_uname => ApeSyscall::Uname,
        __NR_getpid => ApeSyscall::GetPid,
        __NR_gettid => ApeSyscall::GetTid,
        __NR_getppid => ApeSyscall::GetPpid,
        __NR_set_tid_address => ApeSyscall::SetTidAddress,
        __NR_brk => ApeSyscall::Brk,
        __NR_mmap => ApeSyscall::Mmap,
        __NR_mprotect => ApeSyscall::Mprotect,
        __NR_munmap => ApeSyscall::Munmap,
        __NR_mremap => ApeSyscall::Mremap,
        __NR_lseek => ApeSyscall::Lseek,
        __NR_fcntl => ApeSyscall::Fcntl,
        __NR_ioctl => ApeSyscall::Ioctl,
        __NR_execve => ApeSyscall::Execve,
        __NR_rt_sigaction => ApeSyscall::RtSigaction,
        __NR_rt_sigsuspend => ApeSyscall::RtSigsuspend,
        __NR_rt_sigprocmask => ApeSyscall::RtSigprocmask,
        __NR_rt_sigpending => ApeSyscall::RtSigpending,
        __NR_rt_sigtimedwait => ApeSyscall::RtSigtimedwait,
        __NR_rt_sigreturn => ApeSyscall::RtSigreturn,
        __NR_set_robust_list => ApeSyscall::SetRobustList,
        __NR_prlimit64 => ApeSyscall::Prlimit64,
        __NR_clock_gettime => ApeSyscall::ClockGettime,
        __NR_gettimeofday => ApeSyscall::Gettimeofday,
        __NR_times => ApeSyscall::Times,
        __NR_nanosleep => ApeSyscall::Nanosleep,
        __NR_ppoll => ApeSyscall::Ppoll,
        __NR_getrandom => ApeSyscall::Getrandom,
        __NR_getuid => ApeSyscall::Getuid,
        __NR_geteuid => ApeSyscall::Geteuid,
        __NR_getgid => ApeSyscall::Getgid,
        __NR_getegid => ApeSyscall::Getegid,
        __NR_clone => ApeSyscall::Clone,
        __NR_wait4 => ApeSyscall::Wait4,
        __NR_setsid => ApeSyscall::Setsid,
        __NR_getsid => ApeSyscall::Getsid,
        __NR_setpgid => ApeSyscall::Setpgid,
        __NR_getpgid => ApeSyscall::Getpgid,
        __NR_kill => ApeSyscall::Kill,
        __NR_reboot => ApeSyscall::Reboot,
        __NR_sched_yield => ApeSyscall::SchedYield,
        __NR_prctl => ApeSyscall::Prctl,
        __NR_futex => ApeSyscall::Futex,
        _ => ApeSyscall::Unsupported,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FutexOpClass {
    Wake,
    Wait,
    Other,
}

pub fn classify_futex_op(futex_op: usize) -> FutexOpClass {
    let cmd = futex_op & FUTEX_CMD_MASK as usize;
    match cmd as u32 {
        FUTEX_WAKE | FUTEX_WAKE_PRIVATE => FutexOpClass::Wake,
        FUTEX_WAIT | FUTEX_WAIT_PRIVATE | FUTEX_WAIT_BITSET | FUTEX_WAIT_BITSET_PRIVATE => {
            FutexOpClass::Wait
        }
        _ => FutexOpClass::Other,
    }
}
